---
- name: KeePass from apt
  apt: name="{{ item }}" state=present update_cache=yes cache_valid_time=60
  with_items:
    - keepass2
    - xdotool
  become: true
  become_user: root

- name: KeePass plugins from apt
  apt: name="{{ item }}" state=present update_cache=yes cache_valid_time=60
  with_items: keepass2_apt_plugins
  become: true
  become_user: root

- name: KeePass plugins from direct download
  get_url: dest="/usr/lib/keepass2/plugins/{{ item.dest }}" url="{{ item.url }}" sha256sum="{{ item.sha256sum }}" owner=root group=root mode=0644
  with_items: keepass2_download_plugins
  become: true
  become_user: root
